databases:
  - name: todolist-db
    plan: free
    databaseName: todolist
    user: todolist

services:
  - type: web
    plan: free
    name: randre-todolist
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JDK_JAVA_OPTIONS
        value: -Xms256m -Xmx512m -Dspring.profiles.active=prod
      - key: DATABASE_URL
        fromDatabase:
          name: todolist-db
          property: connectionString
    numInstances: 1
