databases:
  - name: task-tracker-db
    plan: free
    databaseName: task_tracker
    user: task_tracker

services:
  - type: web
    plan: free
    name: task-tracker-api
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JDK_JAVA_OPTIONS
        value: -Xms256m -Xmx512m -Dspring.profiles.active=prod
      - key: DATABASE_HOST
        fromDatabase:
          name: task-tracker-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: task-tracker-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: task-tracker-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: task-tracker-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: task-tracker-db
          property: password
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_CHAT_MODEL
        sync: false
      - key: GROQ_CHAT_TEMPERATURE
        sync: false

    numInstances: 1
